<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Request # {{$data['OCMRequest'][0]->ReqestID}} | {{$data['OCMRequest'][0]->PatName}}</title>

</head>
<style type="text/css"> 
@page {
    margin-top:20px;
    margin-left:0px;
    margin-right:0px;
    margin-bottom:5px;
    }
    ul {
      padding-left:10px;
    }
    ul li {
      line-height: 1.8;
      font-size: 15px;
    }
    b {
      font-weight: 400;
    }
    p{
      font-size: 15px;
    }

</style>
<body style="font-family: sans-serif;font-size:15px;line-height: 1.4;">
  
                                
          <!-- Main content -->
            <div class="invoice p-3 mb-3" style="width:750px;margin: 0 auto;padding-top: 20px;">
              <!-- title row -->
              <div class="row">
               
                <div class="col-12">
                  

                  <div style="width:110px;display: inline-block;text-align:left;padding-top: 10px;">
                    
                    <img style="width:100px;" src='{{ public_path("images/".$data["business"][0]->file) }}'> 

                  </div>

                   <div style="width: 48%;display: inline-block;text-align:left;margin-top:0px;">
                     <p class="text-dark text-left m-0" style="margin:0;">
                                <b id="patname">{{$data["business"][0]->name}}</b>
                             </p>

                             <p class="text-dark text-left m-0" style="margin:0;">
                                <b id="patname">{{$data["business"][0]->phone}}</b>
                             </p>

                             <p class="text-dark text-left m-0" style="margin:0;">
                                <b id="patname">{{$data["business"][0]->email}}</b>
                             </p>

                             <p class="text-dark text-left m-0" style="margin:0;">
                                <b id="patname">{{$data["business"][0]->address}}</b>
                                <b id="patname">{{$data["business"][0]->city}}</b>
                                <b id="patname">{{$data["business"][0]->state}}</b>
                                <b id="patname">{{$data["business"][0]->country}}</b>
                             </p>
                  </div>

                  
                </div>
                <!-- /.col -->
              </div>



                                            

                <div class="row" style="margin-top:40px">

                <div class="col-md-12">
                  
                  <p><strong>Dear {{$data['GP'][0]->GP_Name}}</strong></p>
                  <p>Please arrange for the following tests for this patient who is attending {{$data['OCMRequest'][0]->Clinician}}</p>

                  <ul style="list-style: none;">
                    <li><b>Patient Name : </b> {{$data['OCMRequest'][0]->PatName}}</li>
                    <li><b>DOB : </b>  
                      {{\App\Http\Controllers\Controller::Date($data['OCMRequest'][0]->DoB)}}
                    </li>
                    <li><b>Chart Number : </b> {{$data['OCMRequest'][0]->Chart}}</li>
                    <li><b>Address : </b> {{$data['OCMRequest'][0]->Address0}}</li>
                    <li><b>Address2 : </b> {{$data['OCMRequest'][0]->Address1}}</li>
                    <li><b>Address 3  :</b> {{$data['OCMRequest'][0]->Address2}}</li>
                  </ul>

                </div>

                <div class="col-md-12">

                  <p class="row"> To have the following investigations carried out for 
                   
                     {{\App\Http\Controllers\Controller::DateTime($data['OCMRequest'][0]->ExecutionDateTime)}}
                   
                   </p>
                  
                    @foreach ($data['OCMRequestDetails'] as $profiles)
                      <div  style="background: #f3f3f3;width: 100%;margin-bottom:5px ;display: inline-block;">
                        <div style="padding: 10px;"><b>{{$profiles->name}}</b></div>
                      </div>
                    @endforeach

                </div>


                <div class="col-md-12">
                  
                  <p style="margin-bottom:5px;"> Request Notes</p>
                  
                  <p style="">  {{$data['OCMRequest'][0]->gpnotes}}</p>

                </div>

                

                                    
            


                <div class="col-md-12">
                  <br> <br> <br> <br>
                  <p style="margin: 0px;"><strong>Request Generated By</strong></p>
                  <p style="margin:0;"> {{Auth::user()->name}} <br/> {{$data['OCMRequest'][0]->Ward}} </p>
                </div>

   


                       
            </div> 

</body>
</html>
